# Copyright 2022 Canonical LTD
# See LICENSE file for licensing details.
#
options:
  registry-server:
    default: rocks.canonical.com/cdk
    type: string
    description: Source registry of metrics server images.
  release:
    type: string
    description: |
      Specify the version of metrics-server as defined by
      https://github.com/kubernetes-sigs/metrics-server/releases

      example)
        juju config kubernetes-metrics-server release='v0.6.1'
      
      A list of supported versions is available through the action:
        juju run-action kubernetes-metrics-server/0 list-releases --wait
      
      To reset by to the latest supported by the charm use:
        juju config kubernetes-metrics-server --reset release
      
      The current release deployed is available by viewing
        juju status kubernetes-metrics-server