name: Test Suite
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Inclusive-naming-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: woke
        uses: canonical-web-and-design/inclusive-naming@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          fail-on-error: true

  lint-and-unit:
    name: Lint & Unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        pip install tox
    - name: Run lint
      run: tox

  charmcraft-build:
    name: Build Charm
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install and prepare LXD snap environment
        run: |
          sudo apt-get remove -qy lxd lxd-client | true
          sudo snap list lxd | true
          sudo snap install lxd --channel=latest/stable
          sudo snap refresh lxd --channel=latest/stable
          sudo lxd waitready
          sudo lxd init --auto
          sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
          sudo lxc network set lxdbr0 ipv6.address none
          sudo usermod -a -G lxd $USER
          sg lxd -c 'lxc version'
      - name: Install Charmcraft
        run: |
          sudo snap install charmcraft --classic --channel=latest/stable
      - name: Build Charm
        run: |
          sg lxd -c 'charmcraft pack'
      - name: Upload charm artifact
        uses: actions/upload-artifact@v3
        with:
          name: kubernetes-metrics-server.charm
          path: ./kubernetes-metrics-server*.charm
      - name: Upload debug artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: charmcraft-logs
          path: /home/runner/snap/charmcraft/common/cache/charmcraft/log/charmcraft-*.log

  integration-test:
    name: Integration tests
    needs: charmcraft-build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
            provider: microk8s
      - name: Download charm artifact
        uses: actions/download-artifact@v3
        with:
          name: kubernetes-metrics-server.charm
      - name: Run test
        run: tox -e integration
      - name: Setup Debug Artifact Collection
        if: ${{ failure() }}
        run: mkdir tmp
      - name: Collect K8s Status
        if: ${{ failure() }}
        run: sudo microk8s.kubectl get all -A 2>&1 | tee tmp/microk8s-status-all.txt
      - name: Collect Juju Status
        if: ${{ failure() }}
        run: sudo juju status 2>&1 | tee tmp/juju-status.txt
      - name: Collect K8s Deployment details
        if: ${{ failure() }}
        run: sudo microk8s.kubectl describe deployments -A 2>&1 | tee tmp/microk8s-deployments.txt
      - name: Collect K8s DaemonSet details
        if: ${{ failure() }}
        run: sudo microk8s.kubectl describe apiservice -A 2>&1 | tee tmp/microk8s-apiservice.txt
      - name: Collect K8s pod logs
        if: ${{ failure() }}
        run: |
          for ns in `sudo microk8s.kubectl get pods -A | awk '{printf "%s;%s\n",$1,$2 }' | grep -v NAME`; do
            NS_POD=(${ns//;/' '})
            echo "Pod logs for: $NS_POD"
            echo "----------------------------------"
            sudo microk8s.kubectl logs ${NS_POD[1]} -n ${NS_POD[0]} 2>&1 | tee tmp/pod-${NS_POD[0]}-logs.txt
            echo
            echo
          done
      - name: Collect microk8s snap logs
        if: ${{ failure() }}
        run: sudo snap logs -n 300 microk8s 2>&1 | tee tmp/snap-log-microk8s.txt
      - name: Collect Juju logs for kubernetes-metrics-server-operator
        if: ${{ failure() }}
        run: sudo juju debug-log --replay --no-tail -i kubernetes-metrics-server-operator | tee tmp/unit-kubernetes-metrics-server-operator-0.log
      - name: Upload debug artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-run-artifacts
          path: tmp